import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'

type Coupon = { id: string; code: string; discount_percent: number; active: boolean; expires_at: string | null; usage_limit: number | null; used_count: number }
export default function AdminCouponsPage() {
  const [coupons, setCoupons] = useState<Coupon[]>([])
  const [message, setMessage] = useState('')
  const [form, setForm] = useState({ code: '', discountPercent: '10', expiresAt: '', usageLimit: '' })
  useEffect(() => { fetch('/api/coupons-admin').then((response) => response.ok ? response.json() : Promise.reject()).then(setCoupons).catch(() => setMessage('Faça login no admin e execute scripts/commerce.sql no Supabase.')) }, [])
  async function createCoupon(event: FormEvent) { event.preventDefault(); const response = await fetch('/api/coupons-admin', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok) return setMessage(result.error || 'Não foi possível criar o cupom.'); setCoupons((items) => [result, ...items]); setForm({ code: '', discountPercent: '10', expiresAt: '', usageLimit: '' }); setMessage('Cupom criado.') }
  async function toggle(coupon: Coupon) { const response = await fetch('/api/coupons-admin', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: coupon.id, active: !coupon.active }) }); if (!response.ok) return setMessage('Não foi possível atualizar o cupom.'); const result = await response.json(); setCoupons((items) => items.map((item) => item.id === result.id ? result : item)) }
  return <section className="admin-page container"><Link href="/admin" className="back-link">← Voltar ao painel</Link><div className="admin-heading"><div><p className="eyebrow">ÁREA MASTER</p><h1>Cupons de desconto</h1></div></div><form className="admin-form" onSubmit={createCoupon}><div className="form-grid"><label>Código<input required value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value.toUpperCase() })} placeholder="BEMVINDO10" /></label><label>Desconto (%)<input required type="number" min="1" max="100" value={form.discountPercent} onChange={(event) => setForm({ ...form, discountPercent: event.target.value })} /></label><label>Validade<input type="datetime-local" value={form.expiresAt} onChange={(event) => setForm({ ...form, expiresAt: event.target.value })} /></label><label>Limite de usos<input type="number" min="1" value={form.usageLimit} onChange={(event) => setForm({ ...form, usageLimit: event.target.value })} placeholder="Sem limite" /></label></div><button className="primary-button" type="submit">Criar cupom <span>+</span></button>{message && <p className="form-status success">{message}</p>}</form><div className="admin-list"><h2>Cupons cadastrados</h2>{coupons.map((coupon) => <div className="admin-item" key={coupon.id}><span><strong>{coupon.code} · {coupon.discount_percent}%</strong><small>{coupon.active ? 'Ativo' : 'Inativo'} · Usos: {coupon.used_count}{coupon.usage_limit ? `/${coupon.usage_limit}` : ''}</small></span><button type="button" onClick={() => toggle(coupon)}>{coupon.active ? 'Desativar' : 'Ativar'}</button></div>)}</div></section>
}
