import { FormEvent, useEffect, useState } from 'react'

type Coupon = { id: string; code: string; discount_percent: number; active: boolean; expires_at: string | null; usage_limit: number | null; used_count: number }
type Props = { onMessage: (message: string) => void }
export default function AdminCoupons({ onMessage }: Props) {
  const [coupons, setCoupons] = useState<Coupon[]>([])
  const [form, setForm] = useState({ code: '', discountPercent: '10', expiresAt: '', usageLimit: '' })
  useEffect(() => { fetch('/api/coupons-admin').then((response) => response.ok ? response.json() : Promise.reject()).then(setCoupons).catch(() => onMessage('Não foi possível carregar os cupons. Execute scripts/commerce.sql no Supabase.')) }, [onMessage])
  async function createCoupon(event: FormEvent) { event.preventDefault(); const response = await fetch('/api/coupons-admin', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok) return onMessage(result.error || 'Não foi possível criar o cupom.'); setCoupons((items) => [result, ...items]); setForm({ code: '', discountPercent: '10', expiresAt: '', usageLimit: '' }); onMessage('Cupom criado.') }
  async function toggle(coupon: Coupon) { const response = await fetch('/api/coupons-admin', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: coupon.id, active: !coupon.active }) }); if (!response.ok) return onMessage('Não foi possível atualizar o cupom.'); const result = await response.json(); setCoupons((items) => items.map((item) => item.id === result.id ? result : item)) }
  return <div className="coupon-admin"><form className="admin-form" onSubmit={createCoupon}><h2>Novo cupom</h2><div className="form-grid"><label>Código<input required value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value.toUpperCase() })} placeholder="BEMVINDO10" /></label><label>Desconto (%)<input required type="number" min="1" max="100" value={form.discountPercent} onChange={(event) => setForm({ ...form, discountPercent: event.target.value })} /></label><label>Validade<input type="datetime-local" value={form.expiresAt} onChange={(event) => setForm({ ...form, expiresAt: event.target.value })} /></label><label>Limite de usos<input type="number" min="1" value={form.usageLimit} onChange={(event) => setForm({ ...form, usageLimit: event.target.value })} placeholder="Sem limite" /></label></div><button className="primary-button" type="submit">Criar cupom <span>+</span></button></form><div className="admin-list"><h2>Cupons ativos e inativos</h2>{coupons.map((coupon) => <div className="admin-item" key={coupon.id}><span><strong>{coupon.code} · {coupon.discount_percent}%</strong><small>{coupon.active ? 'Ativo' : 'Inativo'} · Usos: {coupon.used_count}{coupon.usage_limit ? `/${coupon.usage_limit}` : ''}</small></span><button type="button" onClick={() => toggle(coupon)}>{coupon.active ? 'Desativar' : 'Ativar'}</button></div>)}</div></div>
}
