import { ChangeEvent, useState } from 'react'

type ProductRow = { name: string; brand: string; category: string; compatibleEquipment: string; price: string; stock: string; discountPercent: string; flashSale: boolean; showInBanner: boolean; image: string; description: string }
type Props = { onMessage: (message: string) => void }
const categories = ['Esteiras', 'Musculação', 'Bicicletas', 'Acessórios', 'Peças diversas']
const blank = (): ProductRow => ({ name: '', brand: '', category: categories[0], compatibleEquipment: '', price: '', stock: '0', discountPercent: '0', flashSale: false, showInBanner: false, image: '', description: '' })
export default function AdminBulkProducts({ onMessage }: Props) {
  const [rows, setRows] = useState<ProductRow[]>([blank(), blank()])
  function update(index: number, field: keyof ProductRow, value: string | boolean) { setRows((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item)) }
  function uploadImage(index: number, event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith('image/')) return onMessage('Selecione um arquivo de imagem válido.'); const reader = new FileReader(); reader.onload = () => update(index, 'image', String(reader.result)); reader.readAsDataURL(file) }
  function addRow() { setRows((items) => [...items, blank()]) }
  function removeRow(index: number) { setRows((items) => items.length > 1 ? items.filter((_, itemIndex) => itemIndex !== index) : items) }
  async function saveAll() { const valid = rows.filter((row) => row.name && row.brand && row.compatibleEquipment && row.price && row.image && row.description); if (!valid.length) return onMessage('Preencha pelo menos uma linha completa para cadastrar.'); if (valid.length !== rows.length) return onMessage('Complete ou remova as linhas vazias antes de salvar.'); for (const row of valid) { const response = await fetch('/api/products', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...row, price: Number(row.price.replace(',', '.')), stock: Number(row.stock) || 0, discountPercent: Number(row.discountPercent) || 0, active: true }) }); if (!response.ok) return onMessage('Não foi possível cadastrar todas as peças.'); } setRows([blank(), blank()]); onMessage(`${valid.length} peças cadastradas com sucesso.`) }
  return <div className="bulk-products"><div className="lead-toolbar"><div><h2>Cadastro em massa</h2><p className="form-hint">Uma linha por peça. A imagem é enviada pelo seu computador.</p></div><button className="outline-button" type="button" onClick={addRow}>Adicionar linha</button></div><div className="bulk-table"><div className="bulk-head"><span>Nome</span><span>Marca</span><span>Categoria</span><span>Compatibilidade</span><span>Preço</span><span>Estoque</span><span>Desconto %</span><span>Imagem</span><span>Descrição</span><span>Oferta</span><span>Banner</span><span /></div>{rows.map((row, index) => <div className="bulk-row" key={index}><input value={row.name} onChange={(event) => update(index, 'name', event.target.value)} placeholder="Inversor" /><input value={row.brand} onChange={(event) => update(index, 'brand', event.target.value)} placeholder="Movement" /><select value={row.category} onChange={(event) => update(index, 'category', event.target.value)}>{categories.map((category) => <option key={category}>{category}</option>)}</select><input value={row.compatibleEquipment} onChange={(event) => update(index, 'compatibleEquipment', event.target.value)} placeholder="Modelo" /><input type="number" min="0" step="0.01" value={row.price} onChange={(event) => update(index, 'price', event.target.value)} placeholder="0,00" /><input type="number" min="0" value={row.stock} onChange={(event) => update(index, 'stock', event.target.value)} placeholder="0" /><input type="number" min="0" max="100" value={row.discountPercent} onChange={(event) => update(index, 'discountPercent', event.target.value)} placeholder="0" /><input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => uploadImage(index, event)} aria-label={`Imagem da peça ${index + 1}`} /><input value={row.description} onChange={(event) => update(index, 'description', event.target.value)} placeholder="Descrição" /><input type="checkbox" checked={row.flashSale} onChange={(event) => update(index, 'flashSale', event.target.checked)} aria-label={`Oferta relâmpago da peça ${index + 1}`} /><input type="checkbox" checked={row.showInBanner} onChange={(event) => update(index, 'showInBanner', event.target.checked)} aria-label={`Banner da peça ${index + 1}`} /><button type="button" onClick={() => removeRow(index)} aria-label="Remover linha">×</button></div>)}</div><button className="primary-button" type="button" onClick={saveAll}>Cadastrar todas as peças <span>→</span></button></div>
}
