import { useEffect, useState } from 'react'

type Status = 'new' | 'contacted' | 'proposal' | 'won' | 'lost'
type Lead = { id: string; created_at: string; name: string; email: string; phone: string; cep: string; city: string; state: string; service_type: string; details: string; equipment: { name: string; quantity: number }[]; estimated_total: number; status: Status; notes: string }
const labels: Record<Status, string> = { new: 'Novo', contacted: 'Em contato', proposal: 'Proposta', won: 'Fechado', lost: 'Perdido' }
type Props = { onMessage: (message: string) => void }
export default function AdminLeads({ onMessage }: Props) {
  const [leads, setLeads] = useState<Lead[]>([])
  const [filter, setFilter] = useState('all')
  useEffect(() => { fetch('/api/leads').then((response) => response.ok ? response.json() : Promise.reject()).then(setLeads).catch(() => onMessage('Não foi possível carregar os leads. Execute scripts/leads.sql no Supabase.')) }, [onMessage])
  async function updateLead(lead: Lead, status: Status, notes = lead.notes) { const response = await fetch('/api/leads', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: lead.id, status, notes }) }); if (!response.ok) return onMessage('Não foi possível atualizar o lead.'); const updated = await response.json(); setLeads((items) => items.map((item) => item.id === updated.id ? updated : item)); onMessage('Lead atualizado.') }
  const visible = filter === 'all' ? leads : leads.filter((lead) => lead.status === filter)
  return <div className="lead-dashboard"><div className="lead-stats">{(['new', 'contacted', 'proposal', 'won'] as Status[]).map((status) => <strong key={status}>{leads.filter((lead) => lead.status === status).length}<small>{labels[status]}</small></strong>)}</div><div className="lead-toolbar"><h2>Solicitações de orçamento</h2><select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">Todos</option>{Object.entries(labels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div>{visible.length === 0 && <p className="form-hint">Nenhuma solicitação nesta etapa.</p>}{visible.map((lead) => <article className="lead-card" key={lead.id}><div className="lead-card-main"><div><span className={`lead-status ${lead.status}`}>{labels[lead.status]}</span><h3>{lead.name}</h3><p>{lead.service_type} · {lead.city}/{lead.state} · {new Date(lead.created_at).toLocaleString('pt-BR')}</p><p><a href={`mailto:${lead.email}`}>{lead.email}</a> · <a href={`tel:${lead.phone}`}>{lead.phone}</a> · CEP {lead.cep}</p></div><strong>R$ {Number(lead.estimated_total).toFixed(2).replace('.', ',')}</strong></div><p className="lead-details">{lead.details}</p><small>{lead.equipment.map((item) => `${item.name} (${item.quantity})`).join(' · ')}</small><div className="lead-actions"><select value={lead.status} onChange={(event) => updateLead(lead, event.target.value as Status)}>{Object.entries(labels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><input defaultValue={lead.notes} placeholder="Observação do atendimento" onBlur={(event) => updateLead(lead, lead.status, event.target.value)} /></div></article>)}</div>
}
