import { FormEvent, useState } from 'react'
import Link from 'next/link'
import { useCustomer, type Customer } from '../components/CustomerContext'

const emptyCustomer: Customer = { name: '', document: '', email: '', phone: '', cep: '', address: '', number: '', city: '', password: '' }
export default function Account() {
  const { customer, signIn, register, signOut } = useCustomer()
  const [mode, setMode] = useState<'login' | 'register'>('login')
  const [form, setForm] = useState(emptyCustomer)
  const [message, setMessage] = useState('')
  function update(field: keyof Customer, value: string) { setForm((current) => ({ ...current, [field]: value })) }
  function submit(event: FormEvent) { event.preventDefault(); const success = mode === 'login' ? signIn(form.email, form.password) : register(form); if (!success) setMessage('E-mail ou senha inválidos.') }
  if (customer) return <section className="container account-page"><p className="eyebrow">ÁREA DO CLIENTE</p><h1>Olá, {customer.name}</h1><p className="account-copy">Sua conta está pronta para agilizar compras e entregas.</p><div className="account-box"><h2>Dados cadastrados</h2><p><strong>E-mail:</strong> {customer.email}</p><p><strong>Entrega:</strong> {customer.address}, {customer.number} - {customer.city} | CEP {customer.cep}</p><button className="outline-button" onClick={signOut} type="button">Sair da conta</button></div><Link href="/products" className="primary-button">Continuar comprando <span>→</span></Link></section>
  return <section className="container account-page"><p className="eyebrow">COMPRA SEGURA</p><h1>{mode === 'login' ? 'Entrar na sua conta' : 'Criar sua conta'}</h1><p className="account-copy">Para finalizar o pedido, crie uma conta com seus dados de entrega.</p><form className="account-form" onSubmit={submit}>{mode === 'register' && <><label>Nome completo<input required value={form.name} onChange={(event) => update('name', event.target.value)} /></label><label>CPF ou CNPJ<input required value={form.document} onChange={(event) => update('document', event.target.value)} /></label><label>Telefone<input required value={form.phone} onChange={(event) => update('phone', event.target.value)} /></label><label>CEP<input required value={form.cep} onChange={(event) => update('cep', event.target.value)} /></label><label>Endereço<input required value={form.address} onChange={(event) => update('address', event.target.value)} /></label><label>Número<input required value={form.number} onChange={(event) => update('number', event.target.value)} /></label><label>Cidade / UF<input required value={form.city} onChange={(event) => update('city', event.target.value)} /></label></>}<label>E-mail<input required type="email" value={form.email} onChange={(event) => update('email', event.target.value)} /></label><label>Senha<input required minLength={6} type="password" value={form.password} onChange={(event) => update('password', event.target.value)} /></label>{message && <p className="form-status">{message}</p>}<button className="primary-button" type="submit">{mode === 'login' ? 'Entrar' : 'Criar conta'} <span>→</span></button></form><button className="account-switch" type="button" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setMessage('') }}>{mode === 'login' ? 'Ainda não tenho conta' : 'Já tenho uma conta'}</button></section>
}
