import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import { useCustomer, type Customer } from '../components/CustomerContext'
import { getProviders, signIn as signInGoogle, useSession } from 'next-auth/react'

type AccountForm = Customer & { password: string }
const emptyCustomer: AccountForm = { name: '', document: '', email: '', phone: '', cep: '', address: '', number: '', complement: '', city: '', password: '' }
export default function Account() {
  const { customer, signIn, register, resendConfirmation, signOut } = useCustomer()
  const { data: socialSession } = useSession()
  const [mode, setMode] = useState<'login' | 'register'>('login')
  const [form, setForm] = useState<AccountForm>(emptyCustomer)
  const [message, setMessage] = useState('')
  useEffect(() => { const user = socialSession?.user; if (user && !customer) setForm((current) => ({ ...current, name: user.name || '', email: user.email || '' })) }, [socialSession, customer])
  function update(field: keyof AccountForm, value: string) { setForm((current) => ({ ...current, [field]: value })) }
  async function lookupCep(value: string) { const cep = value.replace(/\D/g, ''); update('cep', value); if (cep.length !== 8) { update('address', ''); update('city', ''); return } setMessage('Consultando endereço...'); try { const response = await fetch(`/api/cep?cep=${cep}`); const result = await response.json(); if (!response.ok) throw new Error(result.error); update('address', result.address.logradouro || ''); update('city', result.address.localidade ? `${result.address.localidade}/${result.address.uf || ''}` : ''); setMessage('Endereço preenchido pelo CEP. Informe apenas o número e o complemento, se houver.') } catch (error) { update('address', ''); update('city', ''); setMessage(error instanceof Error ? error.message : 'Não foi possível consultar o CEP.') } }
  async function submit(event: FormEvent) { event.preventDefault(); const error = mode === 'login' ? await signIn(form.email, form.password) : await register(form, form.password); if (error) setMessage(error); else if (mode === 'register') setMessage('Conta criada com sucesso. Confira sua caixa de entrada e a pasta de spam.') }
  async function resendEmail() { const error = await resendConfirmation(form.email); setMessage(error || 'Novo e-mail de confirmação enviado. Confira também a pasta de spam.') }
  async function continueWithGoogle() { const providers = await getProviders(); if (!providers?.google) return setMessage('Login com Google ainda não foi configurado. Cadastre as credenciais OAuth na Vercel.'); await signInGoogle('google', { callbackUrl: '/account' }) }
  if (customer) return <section className="container account-page"><p className="eyebrow">ÁREA DO CLIENTE</p><h1>Olá, {customer.name}</h1><p className="account-copy">Sua conta está pronta para agilizar compras e entregas.</p><div className="account-box"><h2>Dados cadastrados</h2><p><strong>E-mail:</strong> {customer.email}</p><p><strong>Entrega:</strong> {customer.address}, {customer.number} - {customer.city} | CEP {customer.cep}</p><button className="outline-button" onClick={signOut} type="button">Sair da conta</button></div><Link href="/products" className="primary-button">Continuar comprando <span>→</span></Link></section>
  return <section className="container account-page"><p className="eyebrow">COMPRA SEGURA</p><h1>{mode === 'login' ? 'Entrar na sua conta' : 'Criar sua conta'}</h1><p className="account-copy">Para finalizar o pedido, crie uma conta com seus dados de entrega.</p><button className="google-button" type="button" onClick={continueWithGoogle}>Continuar com Google</button><div className="account-divider">ou use seu e-mail</div><form className="account-form" onSubmit={submit}>{mode === 'register' && <><label>Nome completo<input required value={form.name} onChange={(event) => update('name', event.target.value)} /></label><label>CPF ou CNPJ<input required value={form.document} onChange={(event) => update('document', event.target.value)} /></label><label>Telefone<input required value={form.phone} onChange={(event) => update('phone', event.target.value)} /></label><label>CEP<input required value={form.cep} onChange={(event) => lookupCep(event.target.value)} placeholder="00000-000" /></label><label>Endereço<input required readOnly value={form.address} placeholder="Preenchido automaticamente pelo CEP" /></label><label>Número<input required value={form.number} onChange={(event) => update('number', event.target.value)} /></label><label>Complemento<input value={form.complement} onChange={(event) => update('complement', event.target.value)} placeholder="Ex.: ap. 33, bloco 12" /></label><label>Cidade / UF<input required readOnly value={form.city} placeholder="Preenchida automaticamente pelo CEP" /></label></>}<label>E-mail<input required type="email" value={form.email} onChange={(event) => update('email', event.target.value)} /></label><label>Senha<input required minLength={6} type="password" value={form.password} onChange={(event) => update('password', event.target.value)} /></label>{message && <p className="form-status">{message}</p>}<button className="primary-button" type="submit">{mode === 'login' ? 'Entrar' : 'Criar conta'} <span>→</span></button></form>{mode === 'register' && <button className="resend-button" type="button" onClick={resendEmail}>Reenviar confirmação</button>}<button className="account-switch" type="button" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setMessage('') }}>{mode === 'login' ? 'Ainda não tenho conta' : 'Já tenho uma conta'}</button></section>
}
