import { ChangeEvent, FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'

type AdminProduct = { id: string; name: string; brand: string; category: string; compatibleEquipment: string; description: string; image: string; price: number; active: boolean }
const storageKey = 'alpha-tec-admin-products-v2'
const categories = ['Esteiras', 'Musculação', 'Bicicletas', 'Acessórios', 'Peças diversas']
const emptyProduct: AdminProduct = { id: '', name: '', brand: '', category: 'Esteiras', compatibleEquipment: '', description: '', image: '', price: 0, active: true }
const formatCurrency = (value: number) => value.toFixed(2).replace('.', ',')
const parseCurrency = (value: string) => { const cleaned = value.replace(/[^0-9,.-]/g, ''); const normalized = cleaned.includes(',') ? cleaned.replace(/\./g, '').replace(',', '.') : cleaned; return Number(normalized) || 0 }

export default function Admin() {
  const [authenticated, setAuthenticated] = useState(false)
  const [login, setLogin] = useState({ username: '', password: '' })
  const [product, setProduct] = useState(emptyProduct)
  const [products, setProducts] = useState<AdminProduct[]>([])
  const [message, setMessage] = useState('')
  const [priceText, setPriceText] = useState('0,00')
  useEffect(() => { setProducts(JSON.parse(localStorage.getItem(storageKey) || '[]').map((item: AdminProduct) => ({ ...item, active: item.active !== false }))) }, [])
  async function signIn(event: FormEvent) { event.preventDefault(); const response = await fetch('/api/admin/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(login) }); if (response.ok) setAuthenticated(true); else setMessage('Usuário ou senha inválidos.') }
  function saveProduct(event: FormEvent) { event.preventDefault(); if (!product.image) return setMessage('Selecione uma imagem para o produto.'); const item = { ...product, price: parseCurrency(priceText), id: product.id || `admin-${Date.now()}` }; const updated = [...products.filter((current) => current.id !== item.id), item]; setProducts(updated); localStorage.setItem(storageKey, JSON.stringify(updated)); setProduct(emptyProduct); setPriceText('0,00'); setMessage('Produto salvo neste navegador.') }
  function editProduct(item: AdminProduct) { setProduct(item); setPriceText(formatCurrency(item.price || 0)); setMessage('') }
  function removeProduct(id: string) { const updated = products.filter((item) => item.id !== id); setProducts(updated); localStorage.setItem(storageKey, JSON.stringify(updated)); setMessage('Produto removido.') }
  function toggleProduct(id: string) { const updated = products.map((item) => item.id === id ? { ...item, active: !item.active } : item); setProducts(updated); localStorage.setItem(storageKey, JSON.stringify(updated)); setMessage('Status do produto atualizado.') }
  function uploadImage(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith('image/')) return setMessage('Selecione um arquivo de imagem válido.'); const reader = new FileReader(); reader.onload = () => setProduct((current) => ({ ...current, image: String(reader.result) })); reader.readAsDataURL(file) }
  if (!authenticated) return <section className="admin-page container"><Link href="/" className="back-link">← Voltar para a loja</Link><div className="admin-login"><p className="eyebrow">ÁREA RESTRITA</p><h1>Painel Master</h1><p>Gerencie produtos, imagens e compatibilidades da Alpha Tec.</p><form onSubmit={signIn}><label>Usuário<input required value={login.username} onChange={(event) => setLogin({ ...login, username: event.target.value })} /></label><label>Senha<input required type="password" value={login.password} onChange={(event) => setLogin({ ...login, password: event.target.value })} /></label>{message && <p className="form-status">{message}</p>}<button className="primary-button" type="submit">Entrar <span>→</span></button></form></div></section>
  return <section className="admin-page container"><div className="admin-heading"><div><p className="eyebrow">ÁREA MASTER</p><h1>Gerenciar catálogo</h1></div><Link href="/products" className="outline-button">Ver catálogo</Link></div><form className="admin-form" onSubmit={saveProduct}><h2>{product.id ? 'Editar produto' : 'Novo produto'}</h2><div className="form-grid"><label>Nome da peça<input required value={product.name} onChange={(event) => setProduct({ ...product, name: event.target.value })} /></label><label>Marca do produto<input required value={product.brand} onChange={(event) => setProduct({ ...product, brand: event.target.value })} placeholder="Ex.: Movement" /></label><label>Categoria<select value={product.category} onChange={(event) => setProduct({ ...product, category: event.target.value })}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label>Equipamentos compatíveis<input required value={product.compatibleEquipment} onChange={(event) => setProduct({ ...product, compatibleEquipment: event.target.value })} placeholder="Ex.: Esteira Movement, LX" /></label><label>Preço (R$)<input type="text" inputMode="decimal" value={priceText} onChange={(event) => setPriceText(event.target.value)} onBlur={() => setPriceText(formatCurrency(parseCurrency(priceText)))} placeholder="0,00" /></label><label className="active-field"><input type="checkbox" checked={product.active} onChange={(event) => setProduct({ ...product, active: event.target.checked })} /> ATIVAR produto no catálogo</label><label className="wide">Imagem do produto<input required={!product.image} type="file" accept="image/png,image/jpeg,image/webp" onChange={uploadImage} />{product.image && <img className="admin-image-preview" src={product.image} alt="Pré-visualização do produto" />}</label><label className="wide">Descrição<textarea required rows={4} value={product.description} onChange={(event) => setProduct({ ...product, description: event.target.value })} /></label></div><button className="primary-button" type="submit">Salvar produto <span>→</span></button>{message && <p className="form-status success">{message}</p>}</form><div className="admin-list"><h2>Produtos cadastrados neste navegador</h2>{products.map((item) => <div className="admin-item" key={item.id}><span><strong>{item.name}</strong><small>{item.brand || 'Marca não informada'} · {item.category} · {item.compatibleEquipment} · {item.active ? 'Ativo' : 'Desativado'}</small></span><label className="active-toggle"><input type="checkbox" checked={item.active} onChange={() => toggleProduct(item.id)} /> ATIVAR</label><button type="button" onClick={() => editProduct(item)}>Editar</button><button type="button" onClick={() => removeProduct(item.id)}>Excluir</button></div>)}</div></section>
}
